### PR TITLE
fix: tx is no longer marked as in progress when rejected

### LINKED ISSUE #673: Transaction displayed as In progress when Rejected.
## Description

Transaction displayed as In progress when Rejected.

## Steps to Reproduce

1. Send the transaction from dapp to the wallet
2. Click on `Reject` in the wallet
3.  Open transactions in the wallet

## Expected behavior

Transaction should be Rejected/Cancelled/any other similar state.

## Screenshots

image

### PR DESCRIPTION
**Pull request by asiaznik**
# Related issues 🔗

Closes vegaprotocol/vegawallet-desktop#673

### CODE REVIEW

File: libs/wallet-ui/src/components/interactions/flows/transaction-review/transaction-review.tsx [hunk 1]
```diff
@@ -116,7 +126,20 @@ export const TransactionReview = ({
         title="Failed to send transaction"
         type={data.error.type}
         message={data.error.error}
-        onClose={onClose}
+        onClose={() => {
+          if (data.transaction) {
+            // this usually happens when there's a traceID mismatch
```
Comment (notbot00) [inline libs/wallet-ui/src/components/interactions/flows/transaction-review/transaction-review.tsx:131]: question: how do you get a traceID mismatch? that should never happen, as far as i know, unless we have some really serious bug somewhere 🤔

File: libs/wallet-ui/src/components/interactions/flows/transaction-review/transaction-review.tsx [hunk 2]
```diff
@@ -116,7 +126,20 @@ export const TransactionReview = ({
...
+            // eagerly mark the current tx as failure
+            dispatch({
+              type: 'UPDATE_TRANSACTION',
+              transaction: {
+                id: data.transaction?.id,
+                status: TransactionStatus.FAILURE,
```
Comment (notbot00) [inline libs/wallet-ui/src/components/interactions/flows/transaction-review/transaction-review.tsx:137]: suggestion (blocking): if you set a failure, can you also add an error prop with some description of why this is marked as failed? when opening the transaction details, it's useful to see what happened

File: libs/wallet-ui/src/components/interactions/flows/transaction-review/transaction-review.tsx (hunk 1 above)
Comment (asiaznik) [reply libs/wallet-ui/src/components/interactions/flows/transaction-review/transaction-review.tsx:131]: It may be the way I'm running it both via app and also via a browser over :34115 🤷🏻 Anyway it didn't let me "finish" the tx so I've found it annoying it was still marked as "in progress".

Comment (notbot00) [reply libs/wallet-ui/src/components/interactions/flows/transaction-review/transaction-review.tsx:131]: gotcha. yeah, we were not able to get around the issue of parallel apps submitting events to the same backend. if this makes it easier to run things, that's great stuff! i was just worried for a minute that it's something else :)

**Review by notbot00 — APPROVED** [review]
