### PR TITLE
fix: explorer links

### LINKED ISSUE #674: 'View in block explorer' link does not work
## Description

'View in block explorer' link is inactive in transaction - it does not redirect/open any page. Similary, in Transactions when transaction is open, there is link `View on block explorer` they should be named the same and both redirects to block explorer.

## Steps to Reproduce

1. Send the transaction from dapp to the wallet
2. Approve it
3. Click the link.

## Expected behavior

Block explorer link should redirect the user to specific transaction in explorer app

## Screenshots

image

### PR DESCRIPTION
**Pull request by asiaznik**
# Related issues 🔗

Closes vegaprotocol/vegawallet-desktop#674

### CODE REVIEW

File: libs/wallet-ui/src/components/interactions/flows/transaction-review/transaction-review.tsx [hunk 1]
```diff
@@ -154,10 +154,8 @@ export const TransactionReview = ({
                 </span>
               </CopyWithTooltip>
             )}
-            {data.transaction.txHash && explorerUrl && (
-              <ExternalLink
-                href={`${explorerUrl}/txs/${data.transaction.txHash}`}
-              >
+            {txUrl(data.transaction.txHash) && (
```
Comment (vacuumdreams) [inline libs/wallet-ui/src/components/interactions/flows/transaction-review/transaction-review.tsx]: suggestion (non-blocking): i think if you'd clean this up and saved it to a variable would look a lot cleaner, and probably could skip the type casting as well, something like:

```
const { getTxUrl } = useExplorerLinks()
const txUrl = getTxUrl(data.transaction.txHash)

{txUrl && <ExternalLink href={txUrl} />}
```

File: libs/wallet-ui/src/components/transaction-details/transaction-details.tsx [hunk 2]
```diff
@@ -35,13 +36,14 @@ type SectionListProps = {
 const compileSectionList = ({
   transaction,
   showStatus,
-  explorerUrl,
+  explorerLinks,
```
Comment (vacuumdreams) [inline libs/wallet-ui/src/components/transaction-details/transaction-details.tsx]: suggestion (non-blocking): i might consider compiling the urls in the parent, and passing them in here as `txUrl, blockUrl` as strings, instead of an object of functions. might help with not having to type cast everywhere with `as string`

File: libs/wallet-ui/src/hooks/use-explorer-url.tsx [hunk 3]
```diff
@@ -9,3 +9,23 @@ export const useExplorerUrl = () => {
...
+  partyUrl: (key: string | null | undefined) => string | undefined
+  blockUrl: (number: string | null | undefined) => string | undefined
+}
+export const useExplorerLinks = (): ExplorerLinks => {
+  const explorerUrl = useExplorerUrl()
+  const base = explorerUrl?.trim().replace(/\/*$/, '')
+  const canCreateLink = (value: string | null | undefined) =>
+    base && value && value.length > 0
+  return {
+    txUrl: (hash: string | null | undefined) =>
```
Comment (vacuumdreams) [inline libs/wallet-ui/src/hooks/use-explorer-url.tsx]: suggestion (non-blocking): i think it would be a lot more intuitive to read if these props were called `getTxUrl`, `getPartyUrl`, `getBlockUrl`. otherwise i'd assume they are not functions but strings

**Review by vacuumdreams — APPROVED** [review]

**Review by notbot00 — APPROVED** [review]
