### PR TITLE
fix: error messages

### LINKED ISSUE #34: Fix regression issues
- error messages not displayed properly

### PR DESCRIPTION
**Pull request by notbot00**
# Related issues 🔗

Closes #34 

# Description ℹ️

Fixes the displaying the data on error messages.

### CODE REVIEW

File: libs/wallet-ui/src/hooks/use-import-network.tsx [hunk 1]
```diff
@@ -56,6 +57,7 @@ export function useImportNetwork() {
       } catch (err: unknown) {
         setError(`${err}`)
         setStatus(FormStatus.Error)
+        logger.error(err)
```
Comment (MadalinaRaicu) [inline libs/wallet-ui/src/hooks/use-import-network.tsx:60]: it would be good to add logger as a dependency in the callback, otherwise it LGTM

**Review by MadalinaRaicu — APPROVED** [review]

File: libs/wallet-ui/src/hooks/use-import-network.tsx (hunk 1 above)
Comment (notbot00) [reply libs/wallet-ui/src/hooks/use-import-network.tsx:58]: true, added, thanks!
