### PR TITLE
fix: permissions

### LINKED ISSUE #68: Fix permissions
## Description

Since permission keys are not a negative list as previously assumed, we need to make some changes in order to support the functionality and how it really works on the backend, which is represented by the following structure:

```
access: read, selectedKey: []  -> all keys
access: none, selectedKey: [] -> no keys
access: read, selectedKey: [ ... , ...]  -> some keys
```

Screenshot 2023-01-18 at 11 03 19

### PR DESCRIPTION
**Pull request by notbot00**
# Related issues 🔗

Closes #68 

# Description ℹ️

Fix conditions for permissions handling (modify so that the restrictedKeys array contains allowed keys as expected by the backend - this will be renamed in the next tag to allowedKeys to get rid of the confusion-> https://github.com/vegaprotocol/vega/blob/develop/wallet/api/openrpc.json#L2173-L2179) 

Screenshot 2023-01-19 at 12 26 52
Screenshot 2023-01-19 at 12 27 02

### CODE REVIEW

**Comment by candida-d** [comment]
@notbot00 Are all the actions covered here? If so, maybe we could make the intro copy a little more non-dev friendly? Happy to help work through it with you if that would be useful.

**Comment by candida-d** [comment]
Suggested rewording:

> Choose how much access (app) has to your keys in the wallet ("wallet"):

and then remove the secondary header. 

Additionally, I don't know what the flow is but I wonder if a title of "Update wallet permissions" would make more sense when scanning a list of settings to edit.

**Comment by notbot00** [comment]
Thanks! Updated the copy

Screenshot 2023-01-19 at 12 26 52
Screenshot 2023-01-19 at 12 27 02

File: libs/wallet-ui/src/components/connection-list/connection-manage.tsx [hunk 1]
```diff
@@ -81,16 +87,16 @@ const compileSubmissionData = (
 ): WalletModel.Permissions => {
   const dataKeys = Object.keys(formData) as Array<keyof WalletModel.Permissions>
   return dataKeys.reduce<WalletModel.Permissions>((acc, key) => {
-    const p = formData[key]
+    const p = formData[key] as NormalizedPermission
     return {
       ...acc,
       [key]: {
-        access: p.access,
+        access: p.access === 'read-all' ? 'read' : p.access,
```
Comment (dexturr) [inline libs/wallet-ui/src/components/connection-list/connection-manage.tsx:94]: nitpick: magic strings should probably be in an enum or object

Comment (dexturr) [reply libs/wallet-ui/src/components/connection-list/connection-manage.tsx:94]: so if rename is required we don't have to find it everywhere

**Review by dexturr — APPROVED** [review]
LGTM

File: libs/wallet-ui/src/components/connection-list/connection-manage.tsx [hunk 2]
```diff
@@ -49,21 +51,25 @@ const compileDefaultValues = (
   const permissions = permissionAccessKeys.reduce<NormalizedPermissionMap>(
     (acc, key) => {
       const p = walletPermissions[key]
+      const allowedKeys = keyList.reduce<KeyItem[]>((acc, key) => {
```
[the remark this answers is not in the document]
Comment (notbot00) [reply libs/wallet-ui/src/components/connection-list/connection-manage.tsx]: agreed & changed

File: libs/wallet-ui/src/components/connection-list/connection-manage.tsx (hunk 1 above)
Comment (notbot00) [reply libs/wallet-ui/src/components/connection-list/connection-manage.tsx:91]: the reason i've been using the string versions was because the generator compiles the access type to 
```
access: 'read' | 'none'
```

and that's like a painful extra task to transform back and forth when trying to use the generated permission types, so i'll leave this as it is for now
